const products=[
	{id:'1P0221',title:'Bandeja con cotas',category:'Estuches',image:'1P0221.png',description:'Bandeja automontable acotada, versátil para transportar y presentar productos.'},
	{id:'v4G02870001',title:'Estuche para cazoletas',category:'Estuches',image:'RenderEstucheCazoletas.png',description:'Estuche de acabado cuidado para retail y marcas que valoran cada detalle.'},
	{id:'troquel1g0011',title:'Estuche con perforado',category:'Estuches',image:'troquel1g0011.png',description:'Estuche remontable con tapa y perforado para unir piezas y crear composiciones.'},
	{id:'troquel1g0198',title:'Estuche modular',category:'Estuches',image:'img1G0198.png',description:'Formato troquelado diseñado para una fabricación precisa y un montaje ágil.'},
	{id:'troquel1g0102',title:'Estuche kraft',category:'Estuches',image:'troquel1g0102.png',description:'Solución de cartón con un acabado cálido y presencia natural.'},
	{id:'1L0024',title:'Estuche BASTBM01',category:'Estuches',image:'troquel1L0024.png',description:'Envase diseñado para aportar protección y facilidad de manipulación.'},
	{id:'troquel1P0572',title:'Estuche sostenible',category:'Estuches',image:'1P0572.png',description:'Una alternativa reciclable creada para resolver necesidades de packaging a medida.'},
	{id:'troquelComedero',title:'Estuche comedero',category:'Estuches',image:'troquelComedero.png',description:'Diseño funcional para productos con geometrías específicas.'},
	{id:'troquelMando',title:'Estuche para mando',category:'Estuches',image:'troquelMando.png',description:'Formato compacto de protección y presentación para componentes delicados.'},
	{id:'troquelMaleta',title:'Estuche maleta',category:'Estuches',image:'troquelMaleta.png',description:'Estuche resistente con formato de transporte cómodo y seguro.'},
	{id:'troquelCajaB1',title:'Estuche de alta resistencia',category:'Estuches',image:'troquelCajaB1.png',description:'Solución reforzada para proteger el contenido en logística y distribución.'},
	{id:'troquel4e0066',title:'Estuche reciclable',category:'Estuches',image:'Render4e0066-BIS.png',description:'Envase funcional creado con cartón reciclable para proyectos sostenibles.'},
	{id:'jamonero',title:'Packaging gourmet',category:'Estuches',image:'JamoneroSinImpresion.png',description:'Estuche premium preparado para productos de alimentación y regalo.'},
	{id:'cajaB1',title:'Caja de cartón ondulado',category:'Cajas',image:'cajaB1.png',description:'Caja resistente, ligera y reciclable para envíos, almacenaje y distribución.'},
	{id:'troquel1p0391',title:'Caja para botes',category:'Cajas',image:'troquel1p0391.png',description:'Caja a medida con estructura preparada para proteger productos envasados.'},
	{id:'embargos',title:'Bandeja expositora',category:'Expositores',image:'render_embargos.png',description:'Bandeja de presentación que combina protección y visibilidad de producto.'},
	{id:'ExpositorDM',title:'PLV y expositores',category:'Expositores',image:'3D EXPOSITOR DM.png',description:'Expositor de cartón para punto de venta con una presencia profesional.'},
	{id:'troquelMesaFeria',title:'Mesa para feria',category:'Expositores',image:'troquelMesaFeria.png',description:'Estructura expositiva diseñada para ferias, promociones y eventos.'},
	{id:'troquelMuebleMadera',title:'Mueble expositor',category:'Expositores',image:'troquelMuebleMadera.png',description:'Expositor modular para organizar y destacar productos en tienda.'},
	{id:'troquelCaballete',title:'Caballete expositor',category:'Expositores',image:'troquelCaballete.png',description:'Soporte ligero para comunicación visual, información o promociones.'},
	{id:'arbol',title:'Expositor decorativo',category:'Expositores',image:'RenderArbol.png',description:'Pieza creativa que une decoración, exposición y sostenibilidad.'},
	{id:'dianaTiro',title:'Diana de tiro',category:'Expositores',image:'AMI UNO2.png',description:'Expositor lúdico y funcional ideado para activaciones de marca.'},
	{id:'donaciones',title:'Expositor solidario',category:'Expositores',image:'donaciones.png',description:'Contenedor expositivo para campañas, recogidas y acciones especiales.'}
];
const grid=document.querySelector('.catalog-grid');const results=document.querySelector('.catalog-results');const filters=[...document.querySelectorAll('[data-filter]')];const search=document.querySelector('.catalog-search input');const dialog=document.querySelector('.catalog-dialog');const dialogContent=dialog?.querySelector('.catalog-dialog__content');let activeFilter='todos';
const productImage=(product)=>`/assets/catalogo/${encodeURIComponent(product.image)}`;
const render=()=>{const query=search.value.trim().toLocaleLowerCase('es');const visible=products.filter((product)=>{const categoryMatches=activeFilter==='todos'||product.category===activeFilter;const text=`${product.title} ${product.id} ${product.category}`.toLocaleLowerCase('es');return categoryMatches&&text.includes(query)});results.textContent=`${visible.length} ${visible.length===1?'referencia encontrada':'referencias encontradas'}`;grid.innerHTML=visible.length?visible.map((product)=>`<button class="catalog-card" type="button" data-product="${product.id}"><span class="catalog-card__image"><img src="${productImage(product)}" alt="${product.title}" loading="lazy" /></span><span class="catalog-card__body"><span><span class="catalog-card__category">${product.category}</span><h3>${product.title}</h3></span><span class="catalog-card__arrow" aria-hidden="true">↗</span></span></button>`).join(''):'<p class="catalog-empty">No hay referencias que coincidan con la búsqueda.</p>'};
const openProduct=(id)=>{const product=products.find((item)=>item.id===id);if(!product||!dialog||!dialogContent)return;dialogContent.innerHTML=`<img src="${productImage(product)}" alt="${product.title}" /><div class="catalog-dialog__copy"><p class="catalog-eyebrow">${product.category}</p><h2 id="dialog-title">${product.title}</h2><p>${product.description}</p><a href="/#contacto">Solicitar información →</a></div>`;dialog.showModal()};
filters.forEach((button)=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;filters.forEach((item)=>item.classList.toggle('is-active',item===button));render()}));
search?.addEventListener('input',render);grid?.addEventListener('click',(event)=>{const card=event.target.closest('[data-product]');if(card)openProduct(card.dataset.product)});dialog?.querySelector('.catalog-dialog__close')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',(event)=>{if(event.target===dialog)dialog.close()});
const menuButton=document.querySelector('.catalog-menu');const nav=document.querySelector('.catalog-nav');menuButton?.addEventListener('click',()=>{const isOpen=nav.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(isOpen))});nav?.querySelectorAll('a').forEach((link)=>link.addEventListener('click',()=>{nav.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false')}));
render();