const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');
menuButton?.addEventListener('click',()=>{const isOpen=nav.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(isOpen))});
document.querySelectorAll('.nav a').forEach((link)=>link.addEventListener('click',()=>{nav.classList.remove('is-open');menuButton?.setAttribute('aria-expanded','false')}));
const header=document.querySelector('.site-header');
window.addEventListener('scroll',()=>header?.classList.toggle('is-scrolled',window.scrollY>90),{passive:true});
const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12});
document.querySelectorAll('.reveal').forEach((element)=>observer.observe(element));
const countObserver=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(!entry.isIntersecting)return;const element=entry.target;const target=Number(element.dataset.count);const suffix=element.dataset.suffix||'';const duration=1500;const start=performance.now();const animate=(now)=>{const progress=Math.min((now-start)/duration,1);const eased=1-Math.pow(1-progress,3);element.textContent=`${Math.round(target*eased)}${suffix}`;if(progress<1)requestAnimationFrame(animate)};requestAnimationFrame(animate);countObserver.unobserve(element)})},{threshold:.55});
document.querySelectorAll('[data-count]').forEach((element)=>countObserver.observe(element));
const slider=document.querySelector('[data-team-slider]');const track=slider?.querySelector('.impact__track');const cards=track?[...track.children]:[];let sliderIndex=0;let startX=0;let isPointerDown=false;
const updateSlider=()=>{if(!slider||!track||!cards.length)return;const cardWidth=cards[0].getBoundingClientRect().width;const gap=36;sliderIndex=Math.max(0,Math.min(sliderIndex,cards.length-1));track.style.transform=`translateX(${-sliderIndex*(cardWidth+gap)}px)`};
document.querySelector('[data-slider-next]')?.addEventListener('click',()=>{sliderIndex+=1;updateSlider()});
document.querySelector('[data-slider-previous]')?.addEventListener('click',()=>{sliderIndex-=1;updateSlider()});
slider?.addEventListener('pointerdown',(event)=>{startX=event.clientX;isPointerDown=true;slider.setPointerCapture(event.pointerId)});
slider?.addEventListener('pointerup',(event)=>{if(!isPointerDown)return;const moved=event.clientX-startX;if(Math.abs(moved)>45){sliderIndex+=moved<0?1:-1;updateSlider()}isPointerDown=false});
slider?.addEventListener('keydown',(event)=>{if(event.key==='ArrowRight'){sliderIndex+=1;updateSlider()}if(event.key==='ArrowLeft'){sliderIndex-=1;updateSlider()}});
window.addEventListener('resize',updateSlider);
const form=document.querySelector('.contact-form');const status=document.querySelector('.form-status');
form?.addEventListener('submit',async(event)=>{event.preventDefault();status.textContent='Enviando consulta…';const payload=Object.fromEntries(new FormData(form));try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('request');form.reset();status.textContent='Gracias. Nos pondremos en contacto contigo pronto.'}catch{status.textContent='No se pudo enviar. Escríbenos a info@laauxiliar.es'}});
